version: '3'
services:
  devbox:
    build:
      context: ./
      dockerfile: DevBox.DockerFile
    ports:
      - "8004:80"
      - "344:443"
    volumes:
      - "./www/:/var/www/html/"
    depends_on:
      - devmysql
  devmysql:
    build:
      context: ./
      dockerfile: MySQLDev.DockerFile
    ports:
      - "3307:3306"
    volumes:
      - "./data/mysql/:/var/lib/mysql/"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always